### ISSUE TITLE
This crate seems to be unbuildable on Rust 1.34

### ISSUE THREAD

**Issue by Kixunil** [Kixunil/configure_me#33]
https://github.com/romanz/electrs/issues/180

Maybe it can be changed to be buildable? I'm not a fan of dinosaur software, but 1.34 is fairly recent.

**Comment by Kixunil** [comment]
The breakage is due to NLL being introduced in [1.36](https://blog.rust-lang.org/2019/07/04/Rust-1.36.0.html)

So the options are:

1. Keep everything as is, everyone has to upgrade compiler
2. Rewrite the code to be look somewhat retarded, but at least it'd work
3. Update edition

@romanz Electrs is probably the most important non-mine crate using `configure_me`, so how much is <1.36 needed? If you say it's much much needed, I'm probably going to do 2) and create an issue for 3) :)

**Comment by romanz** [comment]
I think that I'll eventually move to latest Rust (when async/await lands on stable) :)

**Comment by Kixunil** [comment]
OK, closing this since the latest changes helped. If anyone hits another issue, feel free to let me know.
