### ISSUE TITLE
Can not build with rust edition 2021 when using configure_me

### ISSUE THREAD

**Issue by ismaelsadeeq** [Kixunil/configure_me#56]
I want to use configure_me in a project but after setting things up when I run.

`cargo build`

I get the error

error: failed to run custom build command for `lndk v0.1.0 (/home/abubakar/Desktop/lnd/lndk)`

Caused by:
  process didn't exit successfully: `/home/abubakar/Desktop/lnd/lndk/target/debug/build/lndk-b641571b19e26f92/build-script-build` (exit status: 1)
  --- stderr
  Error: failed to process manifest: faild to load Cargo manifest from /home/abubakar/Desktop/lnd/lndk/Cargo.toml: unknown variant `2021`, expected `2015` or `2018` for key `package.edition` at line 23 column 1
  
  
Steps to reproduce
- ubuntu 22
- rust `rustc 1.68.0 (2c8cc3432 2023-03-06)`
- in cargo.toml  use
- `edition = "2021"`

The configure me configurations is exactly as specified in https://crates.io/crates/configure_me.

If I add `edition = "2018"` in cargo.toml everything works.
but the project I want to contribute to uses 2021 rust edition.

Thanks for helping.

**Comment by Kixunil** [comment]
Oh, crap, I think this has something to do with parsing `Cargo.toml` and if I fix it it may break MSRV. Thanks for the report! I will need to think a bit about the fix and explore it.

**Comment by Kixunil** [comment]
Turns out the fix was easy. :) I've just released `configure_me_codegen` version 0.4.4 with the fix. You should explicitly specify that version in `Cargo.toml` to ensure nobody tries to build with the old one by accident.

**Comment by ismaelsadeeq** [comment]
:+1:   I just did and it builds. 
Thanks for your swift response.
