### ISSUE TITLE
[Bug] Could not build because of low version of `cargo_toml`

### ISSUE THREAD

**Issue by smallzhongfeng** [Kixunil/configure_me#60]
```
error: failed to select a version for the requirement `cargo_toml = "^0.8.0"`
candidate versions found which didn't match: 0.17.0, 0.16.3, 0.16.2, ...
```
we need to upgrade cargo_toml version, version 0.8.0 has been yanked
![image](https://github.com/Kixunil/configure_me/assets/84573424/b26834af-45ed-47f6-915f-3aa0d21dc8aa)

**Comment by Kixunil** [comment]
That sucks, why was it yanked? Upgrading will bump MSRV but I will look into using ranged versions.

**Comment by smallzhongfeng** [comment]
> That sucks, why was it yanked? 

There may be bugs? I don’t know the specifics either.

**Comment by Kixunil** [comment]
Oh, I think you're using `configure_me_codegen` 0.4.3, try using 0.4.4 instead. I still want to use ranged versions but have to run soon and this should at least help you now.

**Comment by aditanase** [comment]
Happens again, 0.12 was yanked

**Comment by Kixunil** [comment]
I'm sorry folks, I had the fix mostly ready but for some reason which I don't remember I didn't publish it.

FYI you can still force yanked versions with `cargo update` but obviously if you're using the crate with a newer project you'll need higher version anyway.

**Comment by Kixunil** [comment]
A new version with ranged dependency was released, so it should work now. LMK if there's a problem.
